host_assignments:
  DevComputer2:
    sensors:
      - name: "AsusXtionCamera"
    nodes:
      - name: "rviz_launch"
      - name: "joy_node"
      - name: "asus_xtion_front_cam"
        parameters:
          sensor: "AsusXtionCamera"
          sensor_config_package: "crawler_app"
          sensor_config_relative_path: "config/hardware/FrontAsusXtionCamera.yaml"  

  ControlModule1:
    sensors:
      - name: "IMU_RobotshopTM151_3435"
    
    nodes:
      - name: "armed_state_manager_node"
      - name: "servo_hat_node"
      - name: "imu_node1"
        parameters:
          sensor: "IMU_RobotshopTM151_3435"
          sensor_config_package: "crawler_app"
          sensor_config_relative_path: "config/hardware/IMU_RobotshopTM151_3435.yaml"  

      - name: "inertial_sensor_fuser_node"
      - name: "local_pose_fuser_node"
