host_assignments:
  ControlModule1:
    sensors:
      - name: "IMU_RobotshopTM151_3435"
    
    nodes:
      - name: "imu_node1"
        parameters:
          sensor: "IMU_RobotshopTM151_3435"
          sensor_config_package: "crawler_app"
          sensor_config_relative_path: "config/hardware/IMU_RobotshopTM151_3435.yaml"  

      - name: "inertial_sensor_fuser_node"
      - name: "local_pose_fuser_node"
